// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT2hinO7spvsOCnUV797mZHIxEcT5xVyQ',
    appId: '1:1041951798378:web:c5041a481202b69fed8613',
    messagingSenderId: '1041951798378',
    projectId: 'smart-job-recommender-ba5a4',
    authDomain: 'smart-job-recommender-ba5a4.firebaseapp.com',
    storageBucket: 'smart-job-recommender-ba5a4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX_vGnfK4cbkkywlc8N7IVstzGcqIvchQ',
    appId: '1:1041951798378:android:cb8e22b5c2d1478bed8613',
    messagingSenderId: '1041951798378',
    projectId: 'smart-job-recommender-ba5a4',
    storageBucket: 'smart-job-recommender-ba5a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDluFgjrYhupUmJGkRt6RzzygdD37_-zck',
    appId: '1:1041951798378:ios:e90a52ab97b2dc92ed8613',
    messagingSenderId: '1041951798378',
    projectId: 'smart-job-recommender-ba5a4',
    storageBucket: 'smart-job-recommender-ba5a4.firebasestorage.app',
    iosBundleId: 'com.example.smartjobrecommender.smartJobRecommender',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDluFgjrYhupUmJGkRt6RzzygdD37_-zck',
    appId: '1:1041951798378:ios:e90a52ab97b2dc92ed8613',
    messagingSenderId: '1041951798378',
    projectId: 'smart-job-recommender-ba5a4',
    storageBucket: 'smart-job-recommender-ba5a4.firebasestorage.app',
    iosBundleId: 'com.example.smartjobrecommender.smartJobRecommender',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDT2hinO7spvsOCnUV797mZHIxEcT5xVyQ',
    appId: '1:1041951798378:web:d71ca927e4048840ed8613',
    messagingSenderId: '1041951798378',
    projectId: 'smart-job-recommender-ba5a4',
    authDomain: 'smart-job-recommender-ba5a4.firebaseapp.com',
    storageBucket: 'smart-job-recommender-ba5a4.firebasestorage.app',
  );
}
